receivers:
  otlp:
    protocols:
      grpc:
      http:
  zipkin:
processors:
  batch:
    timeout: 10s
  resourcedetection:
    detectors: [ecs,system,env]
exporters:
  datadog:
    env: dev
    service: opentelemetrysample
    version: 1.0.0
    metrics:
      send_monotonic_counter: false
      resource_attributes_as_tags: true
    tags:
      - otlp:tag

    api:
      key: apikey
      site: datadoghq.com
  logging:
    loglevel: debug
extensions:
  health_check:
  pprof:
  zpages:
service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resourcedetection]
      exporters: [datadog,logging,zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch,resourcedetection]
      exporters: [datadog,logging]