receivers:
  prometheus:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
    timeout: 10s
  resourcedetection:
    detectors: [system,env]
  attributes:
    actions:
      - key: environment
        value: dev
        action: insert
      - key: region
        value: us-west-2
        action: insert
exporters:
  logging:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  otlp:
    endpoint: tempo:4007
    tls:
      insecure: true    

extensions:
  health_check:
service:
  telemetry:
    logs:
      level: "debug"
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resourcedetection, attributes]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch,resourcedetection]
      exporters: [logging,prometheusremotewrite]