version: "3.9"
services:
  web:
    build: 
      context: ./
      dockerfile: ./OpenTelemetrySample/Dockerfile
    ports:
      - "5009:80"
      - "5010:5001"
    depends_on:
    - opentelemetry-collector
    environment:
      DD_ENV: "dev"
      DD_SERVICE: "OpenTelemetrySample"
      DD_VERSION: "1.0.0"
      DD_AGENT_HOST: "datadog-agent"
      DD_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED: "true"
      DD_RUNTIME_METRICS_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-collector:4318/api/v1/trace"
      DD_TRACE_ENABLED: "true"
      DD_LOGS_INJECTION: "true"
  datadog-agent:
    image: "gcr.io/datadoghq/agent:latest"
    env_file:
      - ./.secrets.env
    environment:
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel/config.yaml"]
    privileged: true
    volumes:
      - ./etc/otel/otel-collector-config.yaml:/etc/otel/config.yaml
    ports:
      - 4317:4317
      - 4318:4318